from types import Any

class ControlSurface:
    def __init__(self, *a, **k) -> None:
        ...

    def _component_guard(self) -> Any:
        ...

    def _disconnect_and_unregister_all_components(self) -> Any:
        ...

    def _do_receive_midi(self, midi_bytes) -> Any:
        ...

    def _do_receive_midi_chunk(self, midi_chunk) -> Any:
        ...

    def _do_send_midi(self, midi_event_bytes) -> Any:
        ...

    def _flush_midi_messages(self) -> Any:
        ...

    def _get_tasks(self) -> Any:
        ...

    def _init_device_provider(self) -> Any:
        ...

    def _install_forwarding(self, midi_map_handle, control, forwarding_type=1) -> Any:
        ...

    def _install_mapping(self, midi_map_handle, control, parameter, feedback_delay, feedback_map) -> Any:
        ...

    def _merge_midi_data(self, recipient, data, midi_data) -> Any:
        ...

    def _pre_serialize(self) -> Any:
        ...

    def _receive_midi_data(self, recipient, data) -> Any:
        ...

    def _register_component(self, component) -> Any:
        ...

    def _register_control(self, control) -> Any:
        ...

    def _send_midi(self, midi_event_bytes, optimized=True) -> Any:
        ...

    def _set_suppress_rebuild_requests(self, suppress_requests) -> Any:
        ...

    _tasks: Any
    def _translate_message(self, type, from_identifier, from_channel, to_identifier, to_channel) -> Any:
        ...

    def accumulating_midi_messages(self) -> Any:
        ...

    def add_disconnect_listener(self, slot, identify_sender=False, *a, **k) -> Any:
        ...

    def add_received_midi_listener(self, slot, identify_sender=False, *a, **k) -> Any:
        ...

    application: Any
    def build_midi_map(self, midi_map_handle) -> Any:
        ...

    def call_listeners(self, listeners) -> Any:
        ...

    def can_lock_to_devices(self) -> Any:
        ...

    def component_guard(self) -> Any:
        ...

    components: Any
    def connect_script_instances(self, instanciated_scripts) -> Any:
        ...

    controls: Any
    device_provider: Any
    device_provider_class: Any
    def disconnect(self) -> Any:
        ...

    def disconnect_disconnectable(self, slot) -> Any:
        ...

    def disconnect_has_listener(self, slot) -> Any:
        ...

    def disconnect_listener_count(self) -> Any:
        ...

    def find_disconnectable(self, predicate) -> Any:
        ...

    def get_component_by_name(self, component_name) -> Any:
        ...

    def get_control_by_name(self, control_name) -> Any:
        ...

    def get_recipient_for_nonsysex_midi_message(self, midi_bytes) -> Any:
        ...

    def get_registry_entry_for_sysex_midi_message(self, midi_bytes) -> Any:
        ...

    handle_undo_steps: Any
    def has_disconnectable(self, slot) -> Any:
        ...

    def lock_to_device(self, device) -> Any:
        ...

    def notify_disconnect(self, *a, **k) -> Any:
        ...

    def notify_received_midi(self, *a, **k) -> Any:
        ...

    def port_settings_changed(self) -> Any:
        ...

    def preferences(self) -> Any:
        ...

    preferences_key: Any
    def process_midi_bytes(self, midi_bytes, midi_processor) -> Any:
        ...

    def receive_midi(self, midi_bytes) -> Any:
        ...

    def receive_midi_chunk(self, midi_chunk) -> Any:
        ...

    def received_midi_has_listener(self, slot) -> Any:
        ...

    def received_midi_listener_count(self) -> Any:
        ...

    def refresh_state(self) -> Any:
        ...

    def register_disconnectable(self, slot) -> Any:
        ...

    def register_disconnectables(self, disconnectables) -> Any:
        ...

    def register_slot(self, *a, **k) -> Any:
        ...

    def release_controlled_track(self) -> Any:
        ...

    def remove_disconnect_listener(self, slot) -> Any:
        ...

    def remove_received_midi_listener(self, slot) -> Any:
        ...

    def request_rebuild_midi_map(self) -> Any:
        ...

    def restore_bank(self, bank_index) -> Any:
        ...

    root_components: Any
    def schedule_message(self, delay_in_ticks, callback, parameter=None) -> Any:
        ...

    def set_controlled_track(self, track) -> Any:
        ...

    def set_enabled(self, enable) -> Any:
        ...

    def set_feedback_channels(self, channels) -> Any:
        ...

    def set_pad_translations(self, pad_translations) -> Any:
        ...

    def show_message(self, message) -> Any:
        ...

    song: Any
    def suggest_map_mode(self, cc_no, channel) -> Any:
        ...

    def supports_pad_translation(self) -> Any:
        ...

    def suppressing_rebuild_requests(self) -> Any:
        ...

    def toggle_lock(self) -> Any:
        ...

    def unlock_from_device(self, device) -> Any:
        ...

    def unregister_disconnectable(self, slot) -> Any:
        ...

    def update(self) -> Any:
        ...

    def update_display(self) -> Any:
        ...

    def update_display_hook(self) -> Any:
        ...




